export const REASON_CODES = {
  TEMP_HIGH_WARN: "TEMP_HIGH_WARN",
  TEMP_HIGH_CRITICAL: "TEMP_HIGH_CRITICAL",
  TEMP_LOW_WARN: "TEMP_LOW_WARN",
  TEMP_LOW_CRITICAL: "TEMP_LOW_CRITICAL",
  HUMIDITY_HIGH_WARN: "HUMIDITY_HIGH_WARN",
  HUMIDITY_HIGH_CRITICAL: "HUMIDITY_HIGH_CRITICAL",
  HUMIDITY_LOW_WARN: "HUMIDITY_LOW_WARN",
  HUMIDITY_LOW_CRITICAL: "HUMIDITY_LOW_CRITICAL",
  CO2_HIGH_WARN: "CO2_HIGH_WARN",
  CO2_HIGH_CRITICAL: "CO2_HIGH_CRITICAL",
  LIGHT_LOW_WARN: "LIGHT_LOW_WARN",
  LIGHT_HIGH_WARN: "LIGHT_HIGH_WARN",
  PRESENCE_EVENT: "PRESENCE_EVENT",
  THRESHOLD_UPDATED: "THRESHOLD_UPDATED",
  THRESHOLD_SYNC_CONFLICT: "THRESHOLD_SYNC_CONFLICT",
  CONTROL_ACTION_MANUAL: "CONTROL_ACTION_MANUAL",
  AUTHZ_DENIED: "AUTHZ_DENIED",
  POWER_SENSOR_MISSING: "POWER_SENSOR_MISSING",
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];